export const documentTitle = {
  reports: 'Reports - Enigmatix OMS',
  dashboard: 'Dashboard - Enigmatix OMS',
  board: 'Board - Enigmatix OMS',
  manage: 'Manage - Enigmatix OMS',
  clientType: 'Client Type - Enigmatix OMS',
  addClient: 'Add Client - Enigmatix OMS',
  clientList: 'Client List - Enigmatix OMS',
  employeeList: 'Employee List - Enigmatix OMS',
  addEmployee: 'Add Employee - Enigmatix OMS',
  employeeType: 'Employee Type - Enigmatix OMS',
  updateEmployee: 'Update Employee - Enigmatix OMS',
  addEmployeeSalary: 'Add Employee Salary - Enigmatix OMS',
  employeeSalaryList: 'Employee Salary List - Enigmatix OMS',
  updateEmployeeSalary: 'Update Employee Salary - Enigmatix OMS',
  teamList: 'Team List - Enigmatix OMS',
  addTeam: 'Add Team - Enigmatix OMS',
  updateTeam: 'Update Team - Enigmatix OMS',
  roleList: 'Role List - Enigmatix OMS',
  languageList: 'Language List - Enigmatix OMS',
  timeSheet: 'Timesheet - Enigmatix OMS',
  userList: 'User List - Enigmatix OMS',
  addUser: 'Add User - Enigmatix OMS',
  updateUser: 'Update User - Enigmatix OMS',
  userRoleList: 'User Role List - Enigmatix OMS',
  userRole: 'User Role List - Enigmatix OMS',
  addUserRole: 'Add User Role - Enigmatix OMS',
  updateUserRole: 'Update User Role - Enigmatix OMS',
  leave: 'Leave - Enigmatix OMS',
  login: 'Login Page - Enigmatix OMS',
  signup: 'Signup Page - Enigmatix OMS',
  profilePage: 'Profile Page - Enigmatix OMS',
  changePassword: 'Profile | Change Password - Enigmatix OMS',
}
